In [136]:
import numpy as np

In [137]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [139]:
# Find the length of the list a where numbers are negative
len(a[a < 0])

4

### 2. How many positive numbers are there?

In [140]:
# Find the length of the list a where numbers are positive
len(a[a > 0])

5

### 3. How many even positive numbers are there?

In [9]:
# Find the length of the list a where numbers are both positive and even
len(a[(a > 0) & (a % 2 == 0)])

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [141]:
# Find the length of the list a where numbers are positive after adding 3
len(a[(a + 3) > 0])

10

### 5. If you squared each number, what would the new mean and standard deviation be?

In [18]:
# print out the mean of list a
print((a ** 2).mean())
# print out the standard deviation of list a
print((a ** 2).std())

74.0
144.0243035046516


### 6. A common statistical operation on a dataset is centering. 
### This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

In [142]:
# print out the list of a after subtracting the mean of list a from each number
print(a - a.mean())

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


### 7. Calculate the z-score for each data point.

In [143]:
# To find z score subtract the mean from each value in a and then divide them by the standard deviation
print(((a - a.mean()) / a.std()))

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [145]:
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [146]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
# initialize sum_of_a variable
sum_of_a = 0
# loops through every number in a
for num in a:
    # adds every number to sum_of_a
    sum_of_a += num
print(sum_of_a)

55


In [147]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
# initialize min_of_a
min_of_a = 200
# loops through every number in a
for num in a:
    # check to see if num is less than current value of min_of_a
    if num < min_of_a:
        # if num is less than min_of_a set min_of_a to num
        min_of_a = num
print(min_of_a)

1


In [148]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
# initialize max_of_a
max_of_a = 0
# loops through every number in a
for num in a:
    # check to see if num is greater than current value of max_of_a
    if num > max_of_a:
        # if num is greater than max_of_a set it to num
        max_of_a = num
print(max_of_a)

10


In [149]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
#initialize mean_of_a
mean_of_a = 0
#loops through every number in a
for num in a:
    #sum up a list
    mean_of_a += num
# set mean_of_a to sum of a divided by how many numbers in a (ie. the mean)    
mean_of_a = mean_of_a / len(a)
print(mean_of_a)

5.5


In [29]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for num in a:
    product_of_a *= num
product_of_a

3628800

In [32]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = []
for num in a:
    squares_of_a.append(num ** 2)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [34]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for num in a:
    if num % 2 == 1:
        odds_in_a.append(num)
odds_in_a

[1, 3, 5, 7, 9]

In [35]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for num in a:
    if num % 2 == 0:
        evens_in_a.append(num)
evens_in_a

[2, 4, 6, 8, 10]

In [45]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

sumb = 0
for lst in b:
    for num in lst:
        sumb += num
print(f'The sum of b is: {sumb}')

minb = 100
maxb = 0
for lst in b:
    for num in lst:
        if num < minb:
            minb = num
        if num > maxb:
            maxb = num
print(f'The min of b is: {minb}')
print(f'The max of b is: {maxb}')

avgb = 0
count = 0
for lst in b:
    for num in lst:
        avgb += num
        count += 1
avgb = avgb / count
print(f'The avg of b is: {avgb}')

prodb = 1
for lst in b:
    for num in lst:
        prodb *= num
print(f'The product of b is: {prodb}')

bsquare = []
for lst in b:
    for num in lst:
        bsquare.append(num ** 2)
print(f'The list of squares for b is: {bsquare}')

The sum of b is: 33
The min of b is: 3
The max of b is: 8
The avg of b is: 5.5
The product of b is: 20160
The list of squares for b is: [9, 16, 25, 36, 49, 64]


In [48]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
b = np.array(b)
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)
sum_of_b = b.sum()
sum_of_b

33

In [49]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b = b.min()
min_of_b

3

In [51]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b = b.max()
max_of_b

8

In [52]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b = b.mean()
mean_of_b

5.5

In [54]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

product_of_b = b.prod()
product_of_b

20160

In [63]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = [b ** 2]
print(squares_of_b)

[array([[ 9, 16, 25],
       [36, 49, 64]])]


In [64]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)
odds_in_b = b[b % 2 == 1]
print(odds_in_b)

[3 5 7]


In [65]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)
evens_in_b = b[b % 2 == 0]
print(evens_in_b)

[4 6 8]


In [67]:
# Exercise 9 - print out the shape of the array b.
print(b.shape)

(2, 3)


In [150]:
# Exercise 10 - transpose the array b.
print(b.T)

[[3 6]
 [4 7]
 [5 8]]


In [77]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
reshape_b = np.reshape(b, 6)
print(reshape_b)

[3 4 5 6 7 8]


In [80]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
reshape_b = np.reshape(b, (6, 1))
print(reshape_b)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [81]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [85]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)

print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

1
9
45
362880


In [86]:
# Exercise 2 - Determine the standard deviation of c.
print(c.std())

2.581988897471611


In [88]:
# Exercise 3 - Determine the variance of c.
print(round(c.var(), 2))

6.67


In [92]:
# Exercise 4 - Print out the shape of the array c
print(c.shape)

(3, 3)


In [94]:
# Exercise 5 - Transpose c and print out transposed result.
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [99]:
# Exercise 6 - Get the dot product of the array c with c. 
print(c.dot(c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [106]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
sum_c_times_c_trans = np.sum(c * np.transpose(c))
print(sum_c_times_c_trans)

261


In [109]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
prod_c_times_c_trans = np.prod(c * c.transpose())
print(prod_c_times_c_trans)

131681894400


In [134]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

In [118]:
# Exercise 1 - Find the sine of all the numbers in d
sine_d = np.sin(d)
print(sine_d)

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [121]:
# Exercise 2 - Find the cosine of all the numbers in d
cos_d = np.cos(d)
print(cos_d)

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [120]:
# Exercise 3 - Find the tangent of all the numbers in d
tan_d = np.tan(d)
print(tan_d)

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


In [122]:
# Exercise 4 - Find all the negative numbers in d
print(d[d < 0])

[-90 -30 -45 -45]


In [126]:
# Exercise 5 - Find all the positive numbers in d
print(d[d > 0])

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [127]:
# Exercise 6 - Return an array of only the unique numbers in d.
print(np.unique(d))

[-90 -45 -30   0  30  45  60  90 120 180 270]


In [128]:
# Exercise 7 - Determine how many unique numbers there are in d.
print(len(np.unique(d)))

11


In [129]:
# Exercise 8 - Print out the shape of d.
print(d.shape)

(3, 6)


In [132]:
# Exercise 9 - Transpose and then print out the shape of d.
d_transpose = d.transpose()
print(d_transpose)

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [133]:
# Exercise 10 - Reshape d into an array of 9 x 2
reshape_d = d.reshape(9, 2)
print(reshape_d)

[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
